/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.2 public/models/bedroom_interior/scene.gltf
Author: SrMonteiro (https://sketchfab.com/crispimrafael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eloiza-e-ze-newton-45dc277dcb934dbd8d6ca2de38bafa57
Title: Eloiza E Ze Newton
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bedroom(props) {
  const { nodes, materials } = useGLTF('models/bedroom_interior/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[151.433, 0.911, 22.465]} rotation={[-Math.PI / 2, 0, -1.573]} scale={[-0.902, 0.902, 0.902]}>
        <mesh geometry={nodes['������������_Material_#2097633442_0'].geometry} material={materials.Material_2097633442} />
        <mesh geometry={nodes['������������_Material_#2097633442_0_1'].geometry} material={materials.Material_2097633442} />
      </group>
      <group position={[234.117, 50, 142.319]} rotation={[-Math.PI / 2, 0, -0.698]} scale={[-0.576, 0.576, 0.576]}>
        <group position={[-16.115, 34.101, -8.616]} rotation={[-1.567, 1.033, -3.138]} scale={0.177}>
          <group position={[-318.837, 378.588, 117.323]} rotation={[-2.715, 0.198, 2.718]}>
            <mesh geometry={nodes['Calla__Material_#0_0'].geometry} material={materials.Material_0} />
            <mesh geometry={nodes.Calla__Lilia_stem_0.geometry} material={materials.Lilia_stem} />
          </group>
        </group>
        <group position={[0.064, 7.402, 1.145]} rotation={[0, 0, -0.005]} scale={1.116}>
          <mesh geometry={nodes.Box010_water_0.geometry} material={materials.water} position={[9.69, -6.067, 0.072]} />
        </group>
      </group>
      <group position={[-51.636, 191.409, -149.832]} rotation={[-Math.PI / 2, 0, -3.054]}>
        <mesh geometry={nodes['������������_��_����������������009_09P89DFGAE54Q5_0'].geometry} material={materials['09P89DFGAE54Q5']} position={[-7.853, 0.401, -1.965]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.142, 0.13, 0.202]} />
        <mesh geometry={nodes['��������������009_gyituwe55jq4uttghikyitdf_0'].geometry} material={materials.gyituwe55jq4uttghikyitdf} position={[-5.905, 0.328, -0.882]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.162, 0.145, 0.11]} />
        <mesh geometry={nodes['mask_orange_black!!!009_DXRY4SN56SVBFaQA_0'].geometry} material={materials.DXRY4SN56SVBFaQA} position={[3.118, -0.262, 0.005]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.172, 0.157, 0.275]} />
        <mesh geometry={nodes['������������019_uy67_0'].geometry} material={materials.uy67} position={[-3.524, 0.401, -3.025]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.136, 0.115, 0.156]} />
        <mesh geometry={nodes['��������!!!!009_11_-_Default_0'].geometry} material={materials['11_-_Default']} position={[-2.091, 0.401, -1.267]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.139, 0.139, 0.083]} />
        <mesh geometry={nodes.lovesecret009_FGHE567W34T_XFHSJ_0.geometry} material={materials.FGHE567W34T_XFHSJ} position={[-0.913, 0.328, -2.294]} rotation={[-Math.PI / 2, -1.571, 0]} scale={[-0.165, 0.125, 0.073]} />
        <mesh geometry={nodes['hallo!!009_xdfdty34563_0'].geometry} material={materials.xdfdty34563} position={[8.137, 0.401, -1.794]} rotation={[-3.142, -1.434, -1.571]} scale={[-0.142, 0.131, 0.181]} />
      </group>
      <group position={[235.302, 166.379, 142.678]} rotation={[-Math.PI / 2, 0, -1.658]} scale={[0.228, 0.227, 0.248]}>
        <group position={[0, 0, -75.502]}>
          <mesh geometry={nodes.Beat_light_tall001_Case_exterior_0.geometry} material={materials.Case_exterior} />
          <mesh geometry={nodes.Beat_light_tall001_Case_interior_0.geometry} material={materials.Case_interior} />
          <mesh geometry={nodes.Beat_light_tall001_Plastic_0.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Beat_light_tall001_Bulb_0.geometry} material={materials.Bulb} />
        </group>
      </group>
      <group position={[232.474, 52.218, -92.463]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-15.715, 0, 1.109]} rotation={[0, Math.PI / 2, 0]} scale={[1.056, 0.919, 0.952]}>
          <group position={[-15.52, 0, 0]}>
            <mesh geometry={nodes['04_Design_books_655_Cover_17_0'].geometry} material={materials.Cover_17} />
            <mesh geometry={nodes['04_Design_books_655_pages_5_0'].geometry} material={materials.pages_5} />
          </group>
        </group>
        <group position={[-15.715, 0, -1.109]} rotation={[0, Math.PI / 2, 0]} scale={[1.056, 0.919, 0.952]}>
          <group position={[-17.62, 0, 0]}>
            <mesh geometry={nodes['04_Design_books_656_Cover_18_0'].geometry} material={materials.Cover_18} />
            <mesh geometry={nodes['04_Design_books_656_pages_5_0'].geometry} material={materials.pages_5} />
          </group>
        </group>
      </group>
      <group position={[-171.578, 100, -174.175]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Group_001_Color_M03_0.geometry} material={materials.Color_M03} position={[18.634, -3.325, -6.15]} />
      </group>
      <group position={[-70.623, 63.75, -93.395]} rotation={[0, -1.569, 0]}>
        <mesh geometry={nodes['Line012_Material_#63_0'].geometry} material={materials.Material_63} />
        <mesh geometry={nodes['Line012_Material_#61_0'].geometry} material={materials.Material_61} />
        <mesh geometry={nodes['Line012_Material_#62_0'].geometry} material={materials.Material_62} />
      </group>
      <group position={[26.138, 42.6, -2.921]} rotation={[-Math.PI / 2, 0, 3.133]} scale={[0.825, 0.825, 1.004]}>
        <mesh geometry={nodes['41_book4_0'].geometry} material={materials.book4} position={[8.706, -7.339, -0.928]} rotation={[Math.PI / 2, 0.96, Math.PI / 2]} />
        <mesh geometry={nodes['44_pages_0'].geometry} material={materials.pages} position={[1.903, -2.576, -0.392]} rotation={[-Math.PI, 0, 0.611]} />
        <mesh geometry={nodes['43_pages_0'].geometry} material={materials.pages} position={[0.929, -1.818, 1.107]} rotation={[-Math.PI, 0, 0.611]} />
        <mesh geometry={nodes['40_book3_0'].geometry} material={materials.book3} position={[7.732, -6.582, 0.571]} rotation={[Math.PI / 2, 0.96, Math.PI / 2]} />
      </group>
      <group position={[-116.506, 161.91, -151.375]} rotation={[-Math.PI / 2, 0, 0]} scale={0.812}>
        <mesh geometry={nodes.Layer0_001_vray_PDM_Books_07_ksiazki_front_0.geometry} material={materials.vray_PDM_Books_07_ksiazki_front} />
        <mesh geometry={nodes.Layer0_001_vray_PDM_Books_07_ksiazki_bialy_0.geometry} material={materials.vray_PDM_Books_07_ksiazki_bialy} />
        <mesh geometry={nodes.Layer0_001_vray_PDM_Books_07_Redwood_0.geometry} material={materials.vray_PDM_Books_07_Redwood} />
        <mesh geometry={nodes.Layer0_001_vray_PDM_Books_07_ksiazki_kolor_0.geometry} material={materials.vray_PDM_Books_07_ksiazki_kolor} />
        <mesh geometry={nodes.Layer0_001_vray_PDM_Books_07_ksiazki_color_0.geometry} material={materials.vray_PDM_Books_07_ksiazki_color} />
        <mesh geometry={nodes.Layer0_001_vray_PDM_Books_07_ksiazki_bok_0.geometry} material={materials.vray_PDM_Books_07_ksiazki_bok} />
      </group>
      <group position={[-98.899, 0.24, 116.957]} rotation={[-Math.PI / 2, 0, 0.698]} scale={[1.186, 1.186, 1.265]}>
        <group position={[15.524, 38.747, -0.106]}>
          <mesh geometry={nodes['Object018_Material_#2097633434_0'].geometry} material={materials.Material_2097633434} />
          <mesh geometry={nodes['Object018_Material_#2097633434_0_1'].geometry} material={materials.Material_2097633434} />
        </group>
      </group>
      <mesh geometry={nodes['LayerP06_Material_#2097633432_0'].geometry} material={materials.Material_2097633432} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Group_002_Color_M03_0.geometry} material={materials.Color_M03} position={[-171.578, 100, 163.925]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Box015_Material_#353_0'].geometry} material={materials.Material_353} position={[115, 122, -181.5]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Box051_Material_#2097633443_0'].geometry} material={materials.Material_2097633443} position={[44.973, 35.24, 43.788]} rotation={[-Math.PI / 2, 0, 3.138]} scale={0.79} />
      <mesh geometry={nodes['Box056_���������������_0'].geometry} material={materials.material} position={[50.657, 1.212, -33.877]} rotation={[-Math.PI / 2, 0, 3.138]} scale={0.79} />
      <mesh geometry={nodes['Object001_Material_#2097633433_0'].geometry} material={materials.Material_2097633433} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Object004_Material_#2097633466_0'].geometry} material={materials.Material_2097633466} position={[-130.259, 76.774, -150.808]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Object007_vray_<auto>23_0'].geometry} material={materials.vray_auto23} position={[-130.259, 76.774, -150.808]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Object008_Material_#2097633444_0'].geometry} material={materials.Material_2097633444} position={[-70.623, 63.75, -93.395]} rotation={[0, -1.569, 0]} />
      <mesh geometry={nodes.Group_021_vray_Color_008_0.geometry} material={materials.vray_Color_008} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object009_Material_#2097633435_0'].geometry} material={materials.Material_2097633435} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object010_Material_#2097633440_0'].geometry} material={materials.Material_2097633440} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object011_Material_#2097633436_0'].geometry} material={materials.Material_2097633436} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object012_Material_#2097633439_0'].geometry} material={materials.Material_2097633439} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object013_Material_#2097633438_0'].geometry} material={materials.Material_2097633438} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object014_Material_#2097633437_0'].geometry} material={materials.Material_2097633437} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object015_Material_#2097633441_0'].geometry} material={materials.Material_2097633441} position={[-49.258, 91.013, 164.7]} rotation={[-Math.PI / 2, 0, -Math.PI]} />
      <mesh geometry={nodes['Object016_Material_#2097633368_0'].geometry} material={materials.Material_2097633368} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Object017_Material_#2097633369_0'].geometry} material={materials.Material_2097633369} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/bedroom_interior/scene.gltf')
