/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.2 public/models/silvania_e_adilson/scene.gltf
Author: SrMonteiro (https://sketchfab.com/crispimrafael)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/silvania-e-adilson-b0802ae4038048a590635c8e2c64563c
Title: Silvania E Adilson
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ComplexInterior(props) {
  const { nodes, materials } = useGLTF('models/silvania_e_adilson/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['Shape004_Material_#2146804362_0'].geometry} material={materials.Material_2146804362} position={[-119.56, 135.999, -0.366]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Shape005_Material_#2146804362_0'].geometry} material={materials.Material_2146804362} position={[-94.931, 139.5, 6.276]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object410_Material_#2146804363_0'].geometry} material={materials.Material_2146804363} position={[290.674, 269, -4.523]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object411_Material_#2146804362_0'].geometry} material={materials.Material_2146804362} position={[560.961, 165, 352.508]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object413_Material_#2146804362_0'].geometry} material={materials.Material_2146804362} position={[59.557, 165, 352.508]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object416_Material_#2146804367_0'].geometry} material={materials.Material_2146804367} position={[229.191, 137.5, -254.5]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object417_Material_#2146804362_0'].geometry} material={materials.Material_2146804362} position={[31.839, 103.499, -188.442]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Shape028_Material_#2146804360_0'].geometry} material={materials.Material_2146804360} position={[296.84, 138.648, -85.95]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object418_asplenium_adiantum_0.geometry} material={materials.asplenium_adiantum} position={[-71.734, 136.409, -171.491]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object424_Material_#2146804366_0'].geometry} material={materials.Material_2146804366} position={[696.063, 199.348, -83.147]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Box001_Material_#2146804360_0'].geometry} material={materials.Material_2146804360} position={[677.205, 0, -351.82]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/silvania_e_adilson/scene.gltf')
