/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/main_hall/scene.gltf
Author: fangzhangmnm (https://sketchfab.com/fangzhangmnm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/circular-gallery-vr-210066ae665841c9af3a6fed8ec2c36f
Title: Circular Gallery (VR)
*/

import React from 'react'
import { OrbitControls, useGLTF } from '@react-three/drei'
import {useThree} from '@react-three/fiber'

export function MainHall(props) {
  const {camera} = useThree()
  camera.position.set(-10.5,0.8,-8)
  const { nodes, materials } = useGLTF('models/main_hall/scene.gltf')
  return (
    <>
      <OrbitControls camera={camera}/>
      <group  {...props} dispose={null}>
        <group scale={1.458}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Blinds_Wood_Bamboo} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Groundcover_Wood_Mix} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.seabean_clean_middle} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.seabean_clean_top} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.bark} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.leave} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Textile_Maroon} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Textile_Midnight} />
        </group>
        <mesh geometry={nodes.Object_14.geometry} material={materials['Bake_Complex_Baked.001']} scale={1.458} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Bake_Tex_Baked.001']} scale={1.458} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Bake_LF_Baked.001']} scale={1.458} />
      </group>
    </>
  )
}

useGLTF.preload('models/main_hall/scene.gltf')
